### ISSUE TITLE
[Feat] 엔티티 정의

### ISSUE THREAD

**Issue by ErranderLee** [ErranderLee/sugang#1]
**Todo**
- 엔티티 정의
  - [x] 유저 엔티티 정의
  - [x] 과목 엔티티 정의
  - [x] 유저-과목 릴레이션 정의
